# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: setup # module defining setup steps
deploy:
  kubectl:
    manifests: 
    - extras/jwt/jwt-secret.yaml
    - dev-kubernetes-manifests/config.yaml

---

apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: db # module defining database deployments
requires:
  - configs: [setup]
build:
  tagPolicy:
    envTemplate:
      template: "deepfactor"
  local:
    push: false
  artifacts:
  - image: johnkday/accounts-db-bodf
    context: src/accounts-db
  - image: johnkday/ledger-db-bodf
    context: src/ledger-db
deploy:
  kubectl:
    manifests:
    - dev-kubernetes-manifests/accounts-db.yaml
    - dev-kubernetes-manifests/ledger-db.yaml

---

apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: backend # module defining backend services
requires:
  - configs: [db]
build:
  tagPolicy:
    envTemplate:
      template: "deepfactor"
  local:
    push: false
  artifacts:
  - image: johnkday/ledgerwriter-bodf
    jib:
      project: src/ledgerwriter
      fromImage: openjdk:11
  - image: johnkday/balancereader-bodf
    jib:
      project: src/balancereader
      fromImage: openjdk:11
  - image: johnkday/transactionhistory-bodf
    jib:
      project: src/transactionhistory
      fromImage: openjdk:11
  - image: johnkday/contacts-bodf
    context: src/contacts
  - image: johnkday/userservice-bodf
    context: src/userservice
deploy:
  kubectl:
    manifests:
    - dev-kubernetes-manifests/balance-reader.yaml
    - dev-kubernetes-manifests/contacts.yaml
    - dev-kubernetes-manifests/ledger-writer.yaml
    - dev-kubernetes-manifests/transaction-history.yaml
    - dev-kubernetes-manifests/userservice.yaml

---

apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: frontend # module defining frontend service
build:
  tagPolicy:
    envTemplate:
      template: "deepfactor"
  local:
    push: false
  artifacts:
  - image: johnkday/frontend-bodf
    context: src/frontend
deploy:
  kubectl:
    manifests:
    - dev-kubernetes-manifests/frontend.yaml

---

apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: loadgenerator # module defining a load generator service
build:
  tagPolicy:
    envTemplate:
      template: "deepfactor"
  local:
    push: false
  artifacts:
  - image: johnkday/loadgenerator-bodf
    context: src/loadgenerator
deploy:
  kubectl:
    manifests:
    - dev-kubernetes-manifests/loadgenerator.yaml
